### ISSUE TITLE
PUT and DELETE methods error

### ISSUE THREAD

**Issue by devster31** [mapio/nofussbm#2]
I'm using `http` from the package `httpie` to interact with `nofussbm.herokuapp.com`, I tried following the documentation [here](nofussbm.herokuapp.com/signup.html) but this is the error I get:
```
$ echo "[{\"id\":\"577e5290580401000cb1b9c2\",\"date-added\":\"2016-07-07 13:01:04.595000\",\"tags\":\"brew,osx,dependencies,homebrew\",\"title\":\"How to List Brew Dependencies - Zanshin.net\",\"url\":\"http://zanshin.net/2014/02/03/how-to-list-brew-dependencies/\"}]" | http --json --session=nofussbm PUT http://nofussbm.herokuapp.com/api/v1/ --verbose
PUT /api/v1/ HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 345
Content-Type: application/json
Host: nofussbm.herokuapp.com
User-Agent: HTTPie/0.9.3
X-Nofussbm-Key: <mykey>

[
    {
        "date-added": "2016-07-07 13:01:04.595000",
        "id": "577e5290580401000cb1b9c2",
        "tags": "brew,osx,dependencies,homebrew",
        "title": "How to List Brew Dependencies - Zanshin.net",
        "url": "http://zanshin.net/2014/02/03/how-to-list-brew-dependencies/"
    }
]

HTTP/1.1 500 INTERNAL SERVER ERROR
Connection: keep-alive
Content-Length: 291
Content-Type: text/html
Date: Thu, 07 Jul 2016 14:19:21 GMT
Server: gunicorn/19.3.0
Via: 1.1 vegur

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```
and with `DELETE`:
```
$ curl -X DELETE -d @bm.json -H "Content-type: application/json" -H "X-Nofussbm-Key: <mykey>" http://nofussbm.herokuapp.com/api/v1/ -v
*   Trying 54.225.133.127...
* Connected to nofussbm.herokuapp.com (54.225.133.127) port 80 (#0)
> DELETE /api/v1/ HTTP/1.1
> Host: nofussbm.herokuapp.com
> User-Agent: curl/7.43.0
> Accept: */*
> Content-type: application/json
> X-Nofussbm-Key:<mykey>
> Content-Length: 296
>
* upload completely sent off: 296 out of 296 bytes
< HTTP/1.1 500 INTERNAL SERVER ERROR
< Connection: keep-alive
< Server: gunicorn/19.3.0
< Date: Thu, 07 Jul 2016 13:55:46 GMT
< Content-Type: text/html
< Content-Length: 291
< Via: 1.1 vegur
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
* Connection #0 to host nofussbm.herokuapp.com left intact
```
in this case `bm.json` contained:
```json
[
  {
    "id": "577e5290580401000cb1b9c2",
    "date-added": "2016-07-07 13:01:04.595000",
    "tags": "brew,osx,dependencies,homebrew",
    "title": "How to List Brew Dependencies - Zanshin.net",
    "url": "http://zanshin.net/2014/02/03/how-to-list-brew-dependencies/"
  }
]
```
I don't understand if it's a syntax error on my side or if something else is going on.

**Comment by devster31** [comment]
I cloned the repo and put it on heroku, the error seems to be this:
```
2016-07-09T01:00:00.236324+00:00 app[web.1]: Traceback (most recent call last):
2016-07-09T01:00:00.236289+00:00 app[web.1]: [2016-07-09 01:00:00,235] ERROR in app: Exception on /api/v1/ [PUT]
2016-07-09T01:00:00.236325+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
2016-07-09T01:00:00.236327+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
2016-07-09T01:00:00.236328+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2016-07-09T01:00:00.236326+00:00 app[web.1]:     response = self.full_dispatch_request()
2016-07-09T01:00:00.236329+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-07-09T01:00:00.236330+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
2016-07-09T01:00:00.236330+00:00 app[web.1]:     rv = self.dispatch_request()
2016-07-09T01:00:00.236328+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
2016-07-09T01:00:00.236331+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
2016-07-09T01:00:00.236332+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2016-07-09T01:00:00.236333+00:00 app[web.1]:     return f( *args, **kwargs )
2016-07-09T01:00:00.236335+00:00 app[web.1]:     result[ 'error' if ret[ 'err' ] else 'updated' if ret[ 'updatedExisting' ] else 'ignored' ].append( _id )
2016-07-09T01:00:00.236334+00:00 app[web.1]:   File "/app/nofussbm/api.py", line 164, in put
2016-07-09T01:00:00.236336+00:00 app[web.1]: KeyError: 'err'
2016-07-09T01:00:00.236333+00:00 app[web.1]:   File "/app/nofussbm/api.py", line 84, in _f
2016-07-09T01:00:00.236342+00:00 app[web.1]: Traceback (most recent call last):
2016-07-09T01:00:00.236341+00:00 app[web.1]: 2016-07-09 01:00:00 [10] [ERROR] [Flask: nofussbm] Exception on /api/v1/ [PUT]
2016-07-09T01:00:00.236343+00:00 app[web.1]:     response = self.full_dispatch_request()
2016-07-09T01:00:00.236344+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2016-07-09T01:00:00.236342+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
2016-07-09T01:00:00.236343+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
2016-07-09T01:00:00.236344+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
2016-07-09T01:00:00.236346+00:00 app[web.1]:     rv = self.dispatch_request()
2016-07-09T01:00:00.236345+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-07-09T01:00:00.236345+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
2016-07-09T01:00:00.236346+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
2016-07-09T01:00:00.236348+00:00 app[web.1]:   File "/app/nofussbm/api.py", line 164, in put
2016-07-09T01:00:00.236348+00:00 app[web.1]:     result[ 'error' if ret[ 'err' ] else 'updated' if ret[ 'updatedExisting' ] else 'ignored' ].append( _id )
2016-07-09T01:00:00.236347+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2016-07-09T01:00:00.236348+00:00 app[web.1]:     return f( *args, **kwargs )
2016-07-09T01:00:00.236347+00:00 app[web.1]:   File "/app/nofussbm/api.py", line 84, in _f
2016-07-09T01:00:00.236349+00:00 app[web.1]: KeyError: 'err'
2016-07-09T01:00:00.249213+00:00 app[web.1]: 10.155.55.222 - - [09/Jul/2016:01:00:00 +0000] "PUT /api/v1/ HTTP/1.1" 500 291 "-" "HTTPie/0.9.3"
```

**Comment by mapio** [comment]
I was out of office, I'll take care asap :-)

**Comment by mapio** [comment]
It's closed in the above commit. I'll push the changes to Heroku ASAP. Thanks for taking the time to report the issue and sorry for the delay.
